=== emina2222/Provera-znanja/magacin.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.w3schools.com" elementFormDefault="qualified" targetNamespace="http://www.w3schools.com" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="nazivType">
    <xs:restriction base="xs:string">
      <xs:minLength value="3"/>
      <!-- < minimum 3 karaktera > -->
      <xs:maxLength value="30"/>
      <!-- < maksimum 30 karaktera > -->
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="danType">
    <xs:restriction base="xs:integer">
      <xs:pattern value="[1-9]|[1-2][0-9]|3[0-1]"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="mesecType">
    <xs:restriction base="xs:integer">
      <xs:pattern value="[1-9]|1[0-2]"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="cenaType">
    <xs:restriction base="xs:decimal">
      <xs:minExclusive value="1"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="cenaT">
    <xs:simpleContent>
      <xs:extension base="cenaType">
        <xs:attribute name="tip" default="dinari">
          <xs:simpleType>
            <xs:restriction base="xs:NMTOKEN">
              <xs:enumeration value="dinari" />
              <xs:enumeration value="euri" />
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>


  <xs:simpleType name="emailType">
    <xs:restriction base="xs:string">
      <xs:pattern value="\c{5,20}@\c{4,8}.com"></xs:pattern>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="emailT">
    <xs:simpleContent>
      <xs:extension base="emailType">
        <xs:attribute name="tip" use="required">
          <xs:simpleType>
            <xs:restriction base="xs:NMTOKEN">
              <xs:enumeration value="sluzbeni" />
              <xs:enumeration value="privatni" />
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="kompanijaType">
    <xs:sequence>
      <xs:element name="naziv" type="xs:string"></xs:element>
      <xs:element name="adresa" type="xs:string" minOccurs="1"></xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="datumIzradeType">
    <xs:sequence>
      <xs:element name="dan" type="danType"></xs:element>
      <xs:element name="mesec" type="mesecType"></xs:element>
      <xs:element name="godina" type="xs:integer"></xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="adresaT">
    <xs:restriction base="xs:string">
    </xs:restriction>
  </xs:simpleType>


  <xs:complexType name="artikalType">
    <xs:sequence>
      <xs:element name="naziv" type="nazivType" minOccurs="1"></xs:element>
      <xs:element name="datumIzrade" type="datumIzradeType"></xs:element>
      <xs:element name="cena" type="cenaT"></xs:element>
      <xs:element name="kompanija" type="kompanijaType"></xs:element>
      <xs:element name="email" type="emailT" maxOccurs="unbounded"></xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="magacinType">
    <xs:sequence>
      <xs:element name="artikal" type="artikalType"></xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="magacin" type="magacinType"></xs:element>

</xs:schema>

=== emina2222/Provera-znanja/magacin.xml
<?xml version="1.0" encoding="utf-8"?>

<magacin xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="magacin.xsd">
  <artikal>
    <naziv sifra="P11234">Brisac</naziv>
    <datumIzrade>
      <dan>2</dan>
      <mesec>5</mesec>
      <godina>2020</godina>
    </datumIzrade>
    <cena tip="dinari">5000</cena>
    <kompanija>
      <ime>Cepter</ime>
      <adresa>Mestroviceva 8,Beograd</adresa>
    </kompanija>
    <email tip="sluzbeni"></email>
  </artikal>
</magacin>
